export const ADD_DATA = 'ADD_DATA'
export const DELETE_DATA = 'DELETE_DATA'
export const EDIT_DATA = 'EDIT_DATA'
export const SHOW_EDIT = 'SHOW_EDIT'
export const HIDE_EDIT = 'HIDE_EDIT'
export const LOAD_DATA = 'LOAD_DATA'
export const LOAD_DATA_FAILURE = 'LOAD_DATA_FAILURE'
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS'
